Mobile menu
Therealadetunji/Michael_portfolio pull request #10
Opened 2022-06-21 21:48 UTC by Therealadetunji

Add the mobile-menu to the mobile version of my portfolio.
using DOM manipulation in javascript and adding a javascript file to this project.

2022-06-21 22:55 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @Therealadetunji, This is @sja-thedude your code reviewer.

While you made a great effort in this project, I cannot proceed to review your code.

You have submitted a project, that doesn't have commits from both partners in your pair programming group. Kindly make sure all members contribute.

<img width="942" alt="Screenshot 2022-06-22 at 1 51 35 AM" src="https://user-images.githubusercontent.com/70269507/174910013-2644acff-b3fd-475c-8aa7-d87d30cd9952.png">

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-22 09:10 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi Team,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-22 09:10 UTC, Omar-Muhamad commented on script.js
> +};
- [ ] When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears that's not happening So please fix that.

![chrome-capture-2022-5-22](https://user-images.githubusercontent.com/68796232/174990177-fd8004b3-739c-4322-a572-2c3cbb6a6e71.gif)

2022-06-22 10:34 UTC, zieeco approved these changes
# status: APPROVED :green_circle: :100: 

Hi, @Team,


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Nice design 🔥 
✅ Linters are passing 👏 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 10:38 UTC, merged